spring:
  application.name: exam-prep-dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:exam-prep
  h2:
    console:
      enabled: true
  jpa.hibernate.ddl-auto: create
  jms.pub-sub-domain: false
  artemis:
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
